package ru.relex.education.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import ru.relex.education.addressbook.model.ContactData;

import java.util.*;

public class ContactAddTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "D:/WORK/Tester/Java_Selenium/EducRepo2/chromedriver_win32/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    login("admin", "secret");
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void contactAdd() {
    initContactCteate();
    fillContactForm(new ContactData("First Name1", "Middle Name1", "Company 1", "Address 1", "899999999999999"));
    submitContactCreation();
    returnToContactPage();
  }

  private void returnToContactPage() {
    driver.findElement(By.linkText("HOME")).click();
  }

  private void submitContactCreation() {
    driver.findElement(By.cssSelector("input:nth-child(87)")).click();
  }

  private void fillContactForm(ContactData contactData) {
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys(contactData.getFirst_name());
    driver.findElement(By.name("middlename")).click();
    driver.findElement(By.name("middlename")).sendKeys(contactData.getMiddle_name());
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("company")).click();
    driver.findElement(By.name("company")).sendKeys(contactData.getCompany());
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys(contactData.getAddress());
    driver.findElement(By.name("home")).click();
    driver.findElement(By.name("home")).sendKeys(contactData.getPhone());
  }

  private void initContactCteate() {
    driver.findElement(By.linkText("ADD_NEW")).click();
  }

  private void login(String username, String password) {
    driver.get("http://localhost/addressbook/group.php");
    driver.manage().window().setSize(new Dimension(942, 576));
    driver.findElement(By.name("user")).click();
    driver.findElement(By.name("user")).sendKeys(username);
    driver.findElement(By.name("pass")).click();
    driver.findElement(By.name("pass")).sendKeys(password);
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
  }
}
