package ru.relex.education.addressbook.tests;
// Generated by Selenium IDE
import org.junit.Test;
import ru.relex.education.addressbook.model.GroupData;

public class GropCreateTest extends TestBase{

  @Test
  public void testGropCreation() {
    app.gotoGroupPage();
    app.getGroupsHelperr().initGroupCreation();
    app.getGroupsHelperr().fillGroupForm(new GroupData("test1", "test2", "test3"));
    app.getGroupsHelperr().submitGroupCreate();
    app.getGroupsHelperr().returnToGroupPage();
  }

}
