package ru.relex.education.addressbook.tests;
// Generated by Selenium IDE
import org.junit.Assert;
//import org.junit.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ru.relex.education.addressbook.model.GroupData;

import java.util.List;

public class GroupDeleteTest extends TestBase{

  @BeforeMethod
  public void ensurePreconditions() {
    app.goTo().groupPage();
    if (app.group().list().size() == 0) {
      app.group().create(new GroupData().withName("test"));
    }
  }

  @Test
  public void testGroupDelete() {
    ensurePreconditions();
    List<GroupData> before = app.group().list();
    int index = before.size() - 1;
    app.group().delete(index);
    List<GroupData> after = app.group().list();
    //compare elements count
    Assert.assertEquals(after.size(), before.size() - 1);
    before.remove(index);
    //compare elements
    Assert.assertEquals(before, after);
  }
}
