package ru.relex.education.addressbook.tests;
// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import ru.relex.education.addressbook.model.GroupData;

public class GroupDeleteTest extends TestBase{

  @Test
  public void testGroupDelete() {
    app.getNavigationHelper().gotoGroupPage();
    int before = app.getGroupsHelperr().getGroupCount();
    if (! app.getGroupsHelperr().isGroupExist()) {
      app.getGroupsHelperr().createGroup(new GroupData("test1", null, null));
      before = 1;
    }
    app.getGroupsHelperr().selectGroup();
    app.getGroupsHelperr().deleteSelectedGroups();
    app.getGroupsHelperr().returnToGroupPage();
    int after = app.getGroupsHelperr().getGroupCount();
    Assert.assertEquals(after, before - 1);
  }
}
