package ru.relex.education.addressbook.tests;
// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import ru.relex.education.addressbook.model.ContactData;
import ru.relex.education.addressbook.model.GroupData;

import java.util.Comparator;
import java.util.HashSet;
import java.util.List;

public class GroupDeleteTest extends TestBase{

  @Test
  public void testGroupDelete() {
    app.getNavigationHelper().gotoGroupPage();
    if (! app.getGroupsHelperr().isGroupExist()) {
      app.getGroupsHelperr().createGroup(new GroupData("test1", null, null));
    }
    List<GroupData> before = app.getGroupsHelperr().getGroupList();
    app.getGroupsHelperr().selectGroup(before.size() - 1);
    app.getGroupsHelperr().deleteSelectedGroups();
    app.getGroupsHelperr().returnToGroupPage();
    List<GroupData> after = app.getGroupsHelperr().getGroupList();
    Assert.assertEquals(after.size(), before.size() - 1);

    before.remove(before.size() - 1);

    Assert.assertEquals(before, after);
  }
}
